/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gputest_aesByGPU */

#ifndef _Included_com_gputest_aesByGPU
#define _Included_com_gputest_aesByGPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gputest_aesByGPU
 * Method:    testTwo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gputest_aesByGPU_testTwo
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
